### ISSUE TITLE
Tarefas para Execução AC1

### ISSUE THREAD

**Issue by arthuralcorrea** [Time-Winx/estrututura_de_dados#1]
# Tarefas

- [x]  Ordenar Arranjo @arthuralcorreia 
- [x] Encontre o menor número em um arranjo de inteiros desordenado. @EduardoAkira18  
- [x] Encontre o maior número em um arranjo de inteiros desordenado. @Matheus
- [x] Some todos os valores de uma arranjo de inteiros. @Victhoor 
- [x] Conte o número de vezes que um número inteiro aparece em um arranjo. @willalves09 
- [x] Exiba os resultados dos métodos acima para o arranho abaixo. @gtnascimento

**Comment by gtnascimento** [comment]
Exiba os resultados dos métodos acima para o arranho abaixo

Feito.

**Comment by mpollini** [comment]
✔ feito
